### ISSUE TITLE
markdownToHtml throws exception when switching spotbugs plugin from 1.6.1 to 1.6.2

### ISSUE THREAD

**Issue by floscher** [kordamp/markdown-gradle-plugin#24]
Something pretty strange just happened: I wanted to [update some version numbers](https://github.com/JOSM/Mapillary/commit/ae578be88ab1a7a4e11c099b26ac523101a3a97a) for one of my projects. Then [my CI complained that the `markdownToHtml` task failed](https://travis-ci.org/JOSM/Mapillary/jobs/384454382#L593-L599). But I didn't change anything related to the markdown plugin. I'm using version 1.1.0, without any problem so far.

I was able to narrow it down, that when I build my project with the [`com.github.spotbugs` plugin](https://spotbugs.github.io/) in version 1.6.1 everything is fine. As soon as I switch to version 1.6.2 the `markdownToHtml` task breaks.

The error message sounds similar to #14.

Click below to expand the full stacktrace:
<details>

```

> Task :markdownToHtml FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':markdownToHtml'.
> Error creating extended parser class: null

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':markdownToHtml'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: Error creating extended parser class: null
        at org.parboiled.Parboiled.createParser(Parboiled.java:58)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:94)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:63)
        at org.kordamp.gradle.markdown.MarkdownProcessor.getProcessor(MarkdownProcessor.groovy:122)
        at org.kordamp.gradle.markdown.MarkdownProcessor$getProcessor.callCurrent(Unknown Source)
        at org.kordamp.gradle.markdown.MarkdownProcessor.markdownToHtml(MarkdownProcessor.groovy:62)
        at org.kordamp.gradle.markdown.Conversion.convert(Conversion.groovy:58)
        at org.kordamp.gradle.markdown.Conversion$convert$0.call(Unknown Source)
        at org.kordamp.gradle.markdown.MarkdownWorkerImpl$_process_closure1.doCall(MarkdownWorkerImpl.groovy:40)
        at org.kordamp.gradle.markdown.MarkdownWorkerImpl.process(MarkdownWorkerImpl.groovy:33)
        at org.kordamp.gradle.markdown.MarkdownWorker$process.call(Unknown Source)
        at org.kordamp.gradle.markdown.MarkdownToHtmlTask.runTask(MarkdownToHtmlTask.groovy:70)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 29 more
Caused by: java.lang.IllegalStateException
        at org.objectweb.asm.tree.analysis.BasicInterpreter.<init>(BasicInterpreter.java:65)
        at org.parboiled.transform.RuleMethodInterpreter.<init>(RuleMethodInterpreter.java:42)
        at org.parboiled.transform.InstructionGraphCreator.process(InstructionGraphCreator.java:41)
        at org.parboiled.transform.ParserTransformer.runMethodTransformers(ParserTransformer.java:62)
        at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:45)
        at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
        at org.parboiled.Parboiled.createParser(Parboiled.java:54)
        ... 54 more

```

</details>

**Comment by floscher** [comment]
I now replaced this plugin with a custom task for conversion from *.md to *.html (based on [flexmark](https://github.com/vsch/flexmark-java)).

**Comment by aalmiray** [comment]
Fixed with https://github.com/kordamp/markdown-gradle-plugin/commit/9c221add76c790206b4a529e1872bbf641e881e6
